name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  run_ci_cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.8

    - name: Install dependencies
      run: pip install requests jira bs4 Markdown

    - name: Run unravel github client script
      run: |
        python unravel_github_client.py

      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        #API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
